### ISSUE TITLE
Admin Access to this Repo?

### ISSUE THREAD

**Issue by hamelsmu** [jupyterhub/repo2docker-action#40]
@choldgraf @betatim i was wondering if I can get admin access to this repo so I can add/change secrets https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

This will be helpful in continuing to develop this action for example to test something that launches a container in the cloud or pushes to DockerHub or testing/developing other integrations

**Comment by choldgraf** [comment]
done! 👍

**Comment by hamelsmu** [comment]
Thanks 🙏 now I can make some cool things
