### ISSUE TITLE
[Feature Request] Sign commits

### ISSUE THREAD

**Issue by Paveloom** [jupyterhub/repo2docker-action#46]
**Is your feature request related to a problem? Please describe.**
I have a branch protection rule enabled that requires all commits to be signed. When `BINDER_CACHE` is set to any value, the commit that is created is not signed, resulting in a build error.

**Describe the solution you'd like**
Sign commits.

**Describe alternatives you've considered**
As a workaround, I can, of course, disable this branch protection rule.

**Additional context**

![](https://i.imgur.com/iN0NJOM.png)

**Comment by hamelsmu** [comment]
Unfortunately it is not possible to sign conmits made by GitHub Actions.  You would have to have a completely different workflow that involves another actor like a personal access token for a user or another bot. 

This repo is limited to GitHub Actions so I don't see a path to addressing this feature request.   I'll go ahead and close this issue but please feel free to continue the discussion. 

Thanks for your feedback, please let me know how it goes as you use this Action
