### ISSUE TITLE
Document a few image repositories, with some guidance for which to use

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/repo2docker-action#61]
In https://github.com/jupyterhub/repo2docker-action/pull/60 @yuvipanda added some helpful language about recent changes to `DockerHub`'s terms of service, as well as pointers for alternative image repositories to use. There are probably others out there worth documenting as well, and it'd be better if we put _comparisons_ between registries in a standalone section. I think that it'd be most-helpful if we did two things:

1. Provided instructions for a few (maybe the top 3-4?) image repositories.
    - [x] AWS Elastic Container Registry
    - [ ] Google Container Registry (deprecated but popular)
    - [ ] Google Artifact Registry (preferred)
    - [ ] Azure Container Registry

2. Provided a short rubric for deciding between them (even if just a "we recommend this one for the simplest solution")

**Comment by yuvipanda** [comment]
We now have this for quay.io. I think we should have at least for the following:

1. [AWS Elastic Container Registry](https://aws.amazon.com/ecr/)
2. [Google Container Registry](https://cloud.google.com/container-registry) (deprecated but popular)
3. [Google Artifact Registry](https://cloud.google.com/artifact-registry) (preferred)
4. [Azure Container Registry](https://azure.microsoft.com/en-in/services/container-registry/)

Some of these will need #65 fixed as well

**Comment by choldgraf** [comment]
The AWS registry instructions are merged in (#78) and the next one we plan to prioritize is the Google registries. After that it might make sense to open a new issue specifically to track Azure.
