### ISSUE TITLE
Fatal error: Git permissions error on commit local Dockerfile for Binder cache

### ISSUE THREAD

**Issue by wragge** [jupyterhub/repo2docker-action#89]
**Describe the bug**
Docker builds with `BINDER_CACHE` set to `True` suddenly started failing with the error:

```
Commit Local Dockerfile For Binder Cache
  fatal: unsafe repository ('/github/workspace' is owned by someone else)
  To add an exception for this directory, call:
  
  	git config --global --add safe.directory /github/workspace
```
It seems this is due to a security issue in Git: https://github.com/actions/checkout/issues/760

**Comment by dgerosa** [comment]
I'm also having the same issue.

**Comment by yuvipanda** [comment]
Fixed in https://github.com/jupyterhub/repo2docker-action/pull/90 thanks to @jerrybonnell!
