### ISSUE TITLE
curl is broken

### ISSUE THREAD

**Issue by tschm** [jupyterhub/repo2docker-action#99]
**Describe the bug**
Triggering Image Build on mybinder.org. Unfortunately there are moving versions involved. In your container you don't specify the version for curl and users build from scratch. This results for me in 

[527](https://github.com/tschm/antarctic/actions/runs/4704841701/jobs/8344817220#step:4:531)
  curl: (48) An unknown option was passed in to libcurl

**To Reproduce**
This probably fails for any workflow using the repo2docker action. Here's an example: https://github.com/tschm/cs

**Expected behavior**
This used to work until very recently.

**Comment by willow-ahrens** [comment]
I hit this bug as well on my repo, I set continue-on-fail so it looks green for now, but the action did indeed fail with the same bug: https://github.com/willow-ahrens/Finch.jl/actions/runs/4715993868/jobs/8363320585

**Comment by tschm** [comment]
Thank you @willow-ahrens. I think it's a somewhat incomplete installation of curl with the underlying container. This bug is a classic, see for example: https://stackoverflow.com/questions/11678085/curl-48-an-unknown-option-was-passed-in-to-libcurl.

**Comment by tschm** [comment]
I have updated the Dockerfile and created a pull request. The mybinder test is passing. May I please ask @yuvipanda and @hamelsmu to help out?

**Comment by tschm** [comment]
I have released a corrected copy of the workflow, see e.g. here https://github.com/tschm/babynames/blob/main/.github/workflows/binder.yml
It works (for me).

**Comment by willow-ahrens** [comment]
nice! Yeah in the meantime I switched to building my images on github actions and pushing to Docker. I'll try your fork by additionally asking binder to cache the built image.

**Comment by willow-ahrens** [comment]
Yep, it works! (That said, I can't seem to make a build on binder actually work with my github actions workflow).

**Comment by mrakitin** [comment]
We are observing the same problem while publishing the images (https://github.com/bluesky/tutorials/actions/runs/4781987486/jobs/8500926820).

**Comment by tschm** [comment]
@mrakitin 
Please use for now my fork, e.g.

`
# cache for binder
    - name: cache binder build on mybinder.org
      uses: tschm/repo2docker-action@master
      with:
        NO_PUSH: true
        MYBINDERORG_TAG: ${{ github.event.ref }}
`
So instead of using Jupyter-hub use tschm. The only difference between both versions is that I have installed curl-dev in the underlying docker-image of the action. The original repo2-docker-action is currently broken for all users. 

Please switch back to the official version once they have released a correction.

**Comment by tschm** [comment]
The official version has just been updated. Thank you @willow-ahrens @mrakitin for shining some additional light on this problem. And thank you to @hamelsmu for accepting the pull request. I will remove tschm/repo2docker-action within the next few days and close this issue
